BeccaHyland/bike_share

Gemfile.lock, README.md, app/controllers/stations_controller.rb, app/views/stations/index.html.erb, config/routes.rb, coverage/.resultset.json, coverage/index.html, spec/features/station/visitor_sees_all_stations_and_attributes_spec.rb
___X_ Wrote Tests
_X___ Reviewed
* description
closes #2
https://media0.giphy.com/media/mELhJRsNgusO4/giphy.gif
```
```
(╯°□°）╯︵ ┻━┻
=> Adds station index/controller

app/controllers/stations_controller.rb, config/routes.rb, coverage/.resultset.json, coverage/index.html, spec/features/station/visitor_sees_all_stations_and_attributes_spec.rb, spec/features/station/visitor_sees_station_on_show_page_spec.rb
updates all stations and attributes test
__X__ Reviewed
- [] Bug Fix
* description
closes #3 #5 
[](https://media.giphy.com/media/87WdvlESoa640/giphy.gif)
```
```
(╯°□°）╯︵ ┻━┻
=> Adds station path to show name instead of number

app/controllers/stations_controller.rb, app/views/stations/show.html.erb, coverage/.resultset.json, coverage/index.html, spec/features/station/visitor_sees_station_on_show_page_spec.rb
__X_ Wrote Tests
__X__ Reviewed
- [] Bug Fix
* description
closes #4
closes #5
```
```
(╯°□°）╯︵ ┻━┻
=> Adds station show page with attributes

app/controllers/conditions_controller.rb, app/views/conditions/show.html.erb, config/routes.rb, spec/features/conditions/user_sees_a_condition_spec.rb
__x_ Wrote Tests
____ Reviewed
- [] Bug Fix
* description
closes #6
```
```
(╯°□°）╯︵ ┻━┻
=> Condition show

Gemfile, Gemfile.lock, app/controllers/stations_controller.rb, app/models/station.rb, config/initializers/friendly_id.rb, config/routes.rb, db/migrate/20180907195352_create_stations.rb, db/migrate/20180908214734_create_friendly_id_slugs.rb, db/schema.rb, spec/features/stations/visitor_sees_station_on_show_page_spec.rb
__X__ Reviewed
*Fixes URI path for station
*Adds Friendly_ID gem
*Changes tests and controller
```
```
(╯°□°）╯︵ ┻━┻
=> Fixes routing and adds slug for URI

db/migrate/20180909185213_remove_start_station_from_trips.rb, db/migrate/20180909185526_remove_end_station_from_trips.rb, db/schema.rb
__X__ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> removes start and end station indexes from trips table

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20180909164045_create_users.rb, db/schema.rb, spec/features/users/user_can_log_out_spec.rb, spec/features/users/user_can_register_and_login_spec.rb, spec/models/user_spec.rb
__X__ Reviewed
- [] Bug Fix
* Add User Controller
*Add Session Controller
*Add user login/logout funtionality
*Add logic to application_layout for login/logout buttons
*Add logic for Sign In and Sign out
*All tests passing
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> User model

app/controllers/dashboard_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/views/layouts/application.html.erb, config/routes.rb, db/schema.rb, spec/features/users/user_can_register_and_login_spec.rb
_x___ Wrote Tests
___x_ Reviewed
- [] Bug Fix
* description: user_dashboard and proper reirects after logging in or creating an account
closes # 16, 17, 18
```
```
(╯°□°）╯︵ ┻━┻
=> working user dashboard (no user info taken yet)

app/models/item.rb, db/migrate/20180909213755_create_items.rb, db/schema.rb, spec/models/item_spec.rb
__X__ Reviewed
- [] Bug Fix
*Add Item model
*Add validations
*All tests passing
closes #27 
```
```
(╯°□°）╯︵ ┻━┻
=> Add item model

app/views/items/index.html.erb, spec/features/bike_shop/visitor_can_visit_bike_shop_spec.rb
__X__ Reviewed
- [] Bug Fix
* Add index controller method
* Add index view
closes #20 
```
```
(╯°□°）╯︵ ┻━┻
=> Item (bike-shop) index

config/routes.rb
__X__ Reviewed
- [] Bug Fix
* Add index route to Item (bike-shop)
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Add index route for items (bike-shop)

app/controllers/items_controller.rb
__x__ Reviewed
* description: Lost some data from different git hub versions, re-added the index controller and added index to routes
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> minor changes to bring up to date

app/views/items/index.html.erb, app/views/items/show.html.erb
__X_ Reviewed
- [] Bug Fix
* Add Add to Cart button on show page
* Add Add to Cart button on index page
closes #21 
```
```
(╯°□°）╯︵ ┻━┻
=> Add to cart buttons on Item index and show views

app/views/sessions/new.html.erb
__X__ Reviewed
- [] Bug Fix
* Fixes unnecessary fields on login page
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Fixes login form

app/models/cart.rb, app/models/cart_item.rb, app/views/cart_items/index.html.erb
___X_ Wrote Tests
__X__ Reviewed
* description
closes #23 
```
```
(╯°□°）╯︵ ┻━┻
=> wrote total method for cart class

.gitignore, db/seeds.rb
____ Reviewed
- [] Bug Fix
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> adds station csv and seeds station create functionality

app/views/layouts/application.html.erb
____ Reviewed
- [] Bug Fix
* description functioning (not pretty) navbar, added setup for boot strap.
closes #64 
#65 
```
```
(╯°□°）╯︵ ┻━┻
=> added bootstrap setup to layouts/application.html.erb

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
__x__ Reviewed
- [] Bug Fix
* description nav bar bootstrap set up
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> attempting to add bootstrap

db/seeds.rb
__X__ Reviewed
- [] Bug Fix
*Add seed instructions for Station
*Add seed instructions for Condition
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Add seeding instructions for stations and conditions

spec/features/cart/visitor_adds_items_to_cart_spec.rb, spec/models/cart_spec.rb
__X__ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> skips broken tests

spec/features/nav/nav_bar_spec.rb
_x___ Wrote Tests
__x__ Reviewed
- [] Bug Fix
* description wrote tests for nav bar
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> tested nav bar

app/models/cart.rb, spec/features/cart/visitor_adds_items_to_cart_spec.rb, spec/models/cart_spec.rb
__X__ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> fixes cart-item test

app/controllers/cart_items_controller.rb, app/models/cart.rb, app/models/cart_item.rb, app/views/cart_items/index.html.erb, config/routes.rb, spec/features/cart/visitor_adds_items_to_cart_spec.rb
_X___ Reviewed
- [] Bug Fix
* description
closes #31 #30
```
```
(╯°□°）╯︵ ┻━┻
=> increase-decrease buttons work properly

app/controllers/cart_items_controller.rb, app/models/cart.rb, app/views/cart_items/index.html.erb, config/routes.rb, spec/features/cart/user_can_remove_items_from_cart_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: adds remove item button to cart, it works. still needs flash methods.
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Adds remove item from cart button

app/controllers/stations_dashboard_controller.rb, app/models/station.rb, app/views/stations_dashboard/show.html.erb, config/routes.rb, spec/features/dashboards/registered_user_can_visit_station_dashboard_spec.rb, spec/features/items/user_can_visit_item_show_page_spec.rb, spec/models/station_spec.rb
__X__ Reviewed
- [] Bug Fix
* Add stations-dashboard route
* Add stations-dashboard view
* Add total station count
* Add avg bikes per station
* Add most bikes station
* Add least bikes station
* Add oldest and newest installed station
closes #98 
```
```
(╯°□°）╯︵ ┻━┻
=> Stations dashboard

spec/features/cart/user_can_remove_items_from_cart_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> missed a debug

app/views/cart_items/index.html.erb, spec/features/cart/visitor_adds_items_to_cart_spec.rb
__X__ Reviewed
- [] Bug Fix
* description
closes #91 
```
```
(╯°□°）╯︵ ┻━┻
=> adds button to page, functionality to come later

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/controllers/welcome_controller.rb, app/views/dashboard/show.html.erb, app/views/layouts/application.html.erb, app/views/welcome/index.html.erb, config/routes.rb, spec/features/nav/nav_bar_spec.rb, spec/features/users/user_can_register_and_login_spec.rb
____ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Nav update

spec/features/dashboards/registered_user_visits_trips_dasH_longest_shortest_by_ride_spec.rb
__x__ Reviewed
* description isolated stations with most/least starting points into its own test file.
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> moved problematic test to its own file to avoid the other tests' setups

app/controllers/welcome_controller.rb, spec/features/dashboards/registered_user_visits_trips_dasH_longest_shortest_by_ride_spec.rb, spec/features/dashboards/reistered_user_can_visit_trips_dashboard_spec.rb
____ Reviewed
* Fixed one failing test on trips-dashboard
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> fixes user_can_visit_trips_dashboard test

app/models/trip.rb, spec/models/station_spec.rb
__x__ Reviewed
* description Ian helped me fix the issue!
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> working stations by most starting trips, all test issues are resolved

app/models/trip.rb, spec/models/station_spec.rb
__x__ Reviewed
- [] Bug Fix
* description adds method to TRIP model to find station with most trips as an end point
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> added method for Trip to find station with most trips as an end point

app/models/trip.rb, spec/models/trip_spec.rb
__x__ Reviewed
- [] Bug Fix
* description: Trip model method to find most ridden bike, will eventually be displayed on trips dashboard
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> working trip model method for most ridden bike

app/controllers/admin/trips_controller.rb, app/views/admin/trips/index.html.erb, config/routes.rb, db/schema.rb, spec/features/admin/admin_can_delete_trip_from_index_spec.rb
__X__ Reviewed
- [] Bug Fix
*Add admin trip index delete
*Add admin trip controller
*Add admin trip index view
*Add admin trip delete flash message
closes #93 
```
```
(╯°□°）╯︵ ┻━┻
=> Admin trip index

app/models/item.rb, app/models/order.rb, app/models/order_item.rb, db/migrate/20180912225317_add_status_to_order_items.rb, db/schema.rb, spec/models/order_items_spec.rb
__X__ Reviewed
- [] Bug Fix
*Add order_items model
*Add relationships between orders and items through orderitems
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Add orderitems and relationships between orders and items

spec/models/item_spec.rb, spec/models/order_spec.rb
____ Reviewed
- [] Bug Fix
*Adds relationship tests for Order and Item
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Adds relationship tests for orders and items

app/controllers/admin/trips_controller.rb, app/views/admin/trips/index.html.erb, app/views/admin/trips/show.html.erb, spec/features/admin/admin_can_view_trip_show_spec.rb
__X_ Wrote Tests
__X__ Reviewed
- [] Bug Fix
* Add Edit button to admin_show_path
* Add Delete button to admin_show_path
* Add show to admin trip controller
closes #87 
```
```
(╯°□°）╯︵ ┻━┻
=> Add buttons for Edit and Delete on admin show page

app/controllers/admin/conditions_controller.rb, app/views/admin/conditions/_form.html.erb, app/views/admin/conditions/edit.html.erb, config/routes.rb, spec/features/admin/admin_can_edit_conditions_spec.rb
_x__ Wrote Tests
__x__ Reviewed
- [] Bug Fix
* description Admin can Edit a condition
closes #122 
#123 
```
```
(╯°□°）╯︵ ┻━┻
=> Admin condition edit

app/views/admin/trips/index.html.erb
__x__ Reviewed
* takes out CSS class that was giving ambiguous error on button
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Takes out CSS class from Edit button

config/routes.rb
__x__ Reviewed
* Add admin_condition_path and admin_station_path
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Fixes admin routes

app/views/users/new.html.erb, spec/features/users/user_can_register_and_login_spec.rb
__x__ Reviewed
* stacks up sign up form instead of inline.
closes #
https://www.youtube.com/watch?v=oHg5SJYRHA0
```
```
(╯°□°）╯︵ ┻━┻
=> Stacks up sign up form instead of inline

app/views/admin/stations/index.html.erb, spec/features/admin/stations/admin_creates_new_station_spec.rb
__x_ Wrote Tests
____ Reviewed
- [] Bug Fix
* description - adds "ADD NEW STATION" button to admin station index
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> adds test and button on index for admin create station

spec/features/users/user_can_register_and_login_spec.rb
____ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> removes save_and_open_page

app/assets/stylesheets/application.scss, app/views/items/index.html.erb, app/views/items/show.html.erb, db/seeds.rb, spec/features/items/user_can_visit_item_show_page_spec.rb
__X__ Reviewed
- [] Bug Fix
Adds image to item show page.  updates styling.  adds new image to see file
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> updates images show and index pages

Gemfile, Gemfile.lock, app/models/user.rb
__x__ Reviewed
* Removes whitespace from :username field when creating user
*Add auto_strip attributes
closes #162 
```
```
(╯°□°）╯︵ ┻━┻
=> Adds auto_strip_attributes gem to remove whitespace from usernames

app/controllers/admin/conditions_controller.rb, app/views/conditions/index.html.erb, app/views/conditions/show.html.erb, spec/features/admin/admin_can_delete_condition_on_show_index_spec.rb, spec/features/admin/admin_can_nav_to_conditions_edit_spec.rb, spec/features/conditions/user_sees_all_conditions_spec.rb
__X__ Reviewed
* Creates edit and delete functions for admin user on conditions show and index
Creates nav buttons to move back and forth between condition index and show
closes #124 #119 #97 #95
```
```
(╯°□°）╯︵ ┻━┻
=> Condition edit delete

Gemfile.lock, app/controllers/cart_items_controller.rb, spec/features/bike_shop/user_sees_flash_confirmation_cart_item_spec.rb
__X__ Reviewed
- [] Bug Fix
* Adds flash message when item is added to cart
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> adds flash message to add cart button

app/views/admin/conditions/_form.html.erb, app/views/admin/conditions/new.html.erb, app/views/conditions/index.html.erb
__X__ Reviewed
* Fixes styling for conditions new page
closes #164 
```
```
(╯°□°）╯︵ ┻━┻
=> fixes styling issue on conditions edit

app/views/conditions/show.html.erb
__X__ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> fixes duplicate link on condition show page

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/models/item.rb, app/models/user.rb, app/views/conditions/show.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, db/migrate/20180913213351_add_retired_to_items.rb, db/schema.rb, db/seeds.rb, spec/features/bike_shop/visitor_can_visit_bike_shop_spec.rb
__x__ Reviewed
- [] Bug Fix
* Add status attribute to Item model
* Add random picture for seeding items
* Add enum for retired/active items
* Add if/else logic for disabled button in bike-store index view
* Add if/else logic for disabled button in bike-store show view
closes #173 #29 
```
```
(╯°□°）╯︵ ┻━┻
=> Retired item

app/controllers/dashboard_controller.rb, app/controllers/orders_controller.rb, app/models/order.rb, app/models/order_item.rb, app/views/cart_items/index.html.erb, app/views/dashboard/show.html.erb, config/routes.rb, db/migrate/20180915180852_remove_status_from_order_items.rb, db/migrate/20180915185439_add_quantity_to_order_items.rb, db/schema.rb, spec/features/cart/user_can_checkout_cart_spec.rb, spec/features/dashboards/registered_user_visits_trips_dasH_longest_shortest_by_ride_spec.rb, spec/models/order_items_spec.rb, spec/models/order_spec.rb
__X__ Reviewed
- [] Bug Fix
* description
closes #90 
```
```
(╯°□°）╯︵ ┻━┻
=> gives function to checkout buttons

app/controllers/orders_controller.rb, app/views/trips/index.html.erb, spec/features/trips/visitor_sees_one_trip_spec.rb
__X_ Reviewed
- [] Bug Fix
-Removed 'See Trip' link 
-Creates link to trip show out of 'Trip: 1' etc. 
-Updates test to reflect these changes
closes #179 
```
```
(╯°□°）╯︵ ┻━┻
=> fixed trip index to use trip id as link

app/controllers/application_controller.rb, app/controllers/orders_controller.rb, app/models/order_item.rb, app/views/cart_items/index.html.erb, app/views/dashboard/show.html.erb, app/views/orders/show.html.erb, config/routes.rb, spec/features/orders/user_visits_an_order_show_page_spec.rb, spec/models/order_items_spec.rb
__x__ Reviewed
- [] Bug Fix
* Add order show
* Add show controller method
* Add restriction for making sure current user owns order
closes #94 
```
```
(╯°□°）╯︵ ┻━┻
=> Add order show

app/models/station.rb, app/views/admin/items/_form.html.erb, app/views/sessions/new.html.erb, app/views/stations/show.html.erb, db/seeds.rb, spec/features/admin/items/admin_creates_item_spec.rb, spec/features/stations/visitor_sees_station_on_show_page_spec.rb, spec/models/station_spec.rb
_x_ Wrote Tests
_x_ Implemented
____ Reviewed
- [] Bug Fix
* description - update station show with two working AR methods, drafts test for third
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Station show 2

app/views/admin/items/_form.html.erb, app/views/items/index.html.erb, db/seeds.rb
__X__ Reviewed
Fixed bug in the edit item page to round the price to two decimal places.  Error had to do with how we seeded the items. 
closes #191
```
```
(╯°□°）╯︵ ┻━┻
=> fixes edit item price bug not rounding two decimal places

public/404.html
__X__ Reviewed
* description
closes #198 
```
```
(╯°□°）╯︵ ┻━┻
=> removed Ian from 404

app/views/admin/conditions/_form.html.erb, app/views/admin/trips/_form.html.erb, app/views/layouts/application.html.erb, spec/features/admin/trips/admin_can_create_new_trip_spec.rb, spec/features/admin/trips/admin_can_edit_trip_from_index_page_spec.rb, spec/features/admin/trips/admin_can_edit_trip_show_page_spec.rb
_x_ Implemented
____ Reviewed
* description - limits form fields to 0 as needed, in trip partial form adds alphabetized dropdown to select start station and end station
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Checkin fixes 2

app/controllers/application_controller.rb, app/models/cart.rb, app/views/items/index.html.erb, app/views/layouts/application.html.erb, spec/features/cart/user_sees_a_counter_of_items_in_cart_spec.rb, spec/models/cart_spec.rb
__x__ Reviewed
- [] Bug Fix
*Add instance method to Cart class to count cart_items
*Add cart count to navbar
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Add cart counter in nav

app/controllers/trips_dashboard_controller.rb, app/models/trip.rb, app/views/trips_dashboard/show.html.erb, db/csv/small_trip.csv, spec/features/dashboards/registered_user_can_visit_trips_dashboard_spec.rb, spec/models/station_spec.rb
__x__ Reviewed
- [] Bug Fix
* description view for trips-dashboard
closes #99 
```
```
(╯°□°）╯︵ ┻━┻
=> Building trips dash view

app/controllers/conditions_dashboard_controller.rb, app/controllers/orders_controller.rb, app/views/conditions/index.html.erb, app/views/conditions_dashboard/show.html.erb, app/views/orders/show.html.erb, app/views/stations/index.html.erb, app/views/stations_dashboard/show.html.erb, app/views/trips/index.html.erb, app/views/trips_dashboard/show.html.erb, config/routes.rb, spec/features/cart/user_can_checkout_cart_spec.rb, spec/features/orders/user_visits_an_order_show_page_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #193
closes #196
closes #204
```
```
(╯°□°）╯︵ ┻━┻
=> Checkin fixes 3

app/models/station.rb, app/views/stations/index.html.erb, config/routes.rb
__X__ Reviewed
fixes slugs for stations page
closes #197 
```
```
(╯°□°）╯︵ ┻━┻
=> fixes slug issue for station show

app/controllers/admin/items_controller.rb, app/controllers/conditions_dashboard_controller.rb, app/models/condition.rb, app/views/conditions_dashboard/show.html.erb, config/routes.rb, spec/features/dashboards/registered_user_can_visit_conditions_dashboard_spec.rb
___X_ Wrote Tests
_X___ Reviewed
* description
closes #70 
```
```
(╯°□°）╯︵ ┻━┻
=> add high temp functionality for conditions dash

app/controllers/admin/stations_controller.rb, app/controllers/stations_controller.rb, config/routes.rb, spec/features/dashboards/registered_user_can_visit_conditions_dashboard_spec.rb
___X_ Reviewed
* description
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> fixes station name tests

app/controllers/users_controller.rb, app/views/dashboard/show.html.erb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, spec/features/users/user_can_edit_own_information_spec.rb
__X__ Reviewed
User can edit their information
User cannot edit other users information
closes #27 
```
```
(╯°□°）╯︵ ┻━┻
=> User edit account

app/models/order.rb, db/seeds.rb, spec/models/order_spec.rb
__x_ Wrote Tests
____ Reviewed
- [] Bug Fix
* description - =Order method passing in model for sorting orders by status, returns a hash of statuses and counts as values, adds Orders to Seeds
closes #
```
```
(╯°□°）╯︵ ┻━┻
=> Orders by status
